name: QA

on:
  push:
jobs:

  build_and_scan_amd64:
    strategy:
      fail-fast: false
      matrix:
        version: [9/community, 9/developer, 9/enterprise]
        include:
          - version: 9/community
            tag: 9-community
          - version: 9/developer
            tag: 9-developer
          - version: 9/enterprise
            tag: 9-enterprise
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build --pull -t "sonarqube:${{ matrix.tag }}" "${{ matrix.version }}"
      - uses: actions/setup-java@v3
        name: install JDK
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: grab mend jar
        run: curl https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar --output wss.jar
      - id: secrets
        uses: SonarSource/vault-action-wrapper@2.4.3-1
        with:
          secrets: |
            development/kv/data/mend apikey | mend_api_key;
      - name: run wss
        run: java -jar wss.jar -docker.scanImages true
        env:
          WS_WSS_URL: https://saas-eu.whitesourcesoftware.com/agent
          WS_APIKEY: ${{ fromJSON(steps.secrets.outputs.vault).mend_api_key }}
          WS_PRODUCTNAME: SonarSource/docker-sonarqube
      